services:
  - type: web
    name: monsite
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn monsite.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: monsite.settings
